/*
 *	Version : @(#)locate.h	1.3	96/10/25
 */

/**************************************************************************
**                                                                        *
**  FILE        :  locate.h                                               *
**                                                                        *
**  DESCRIPTION :  Definitions used in locator generated tables		  *
**                                                                        *
**  COPYRIGHT   :  1996 Tasking Software B.V., Amersfoort                 *
**                                                                        *
**************************************************************************/

#ifndef	LOCATE_INC

/*
** Copy table
** ==========
**
** Generated by the locator if label __lc_cp is used.
**
** Layout of a copy table entry:
**
** <action> <destination> <source> <length>
**
** action:	defines which action has to be taken for the current entry
**		(See 'CP' defines below) Valid actions:
**              0:        End of copy table reached, no actions
**		CP_COPY:  Copy <length> bytes from <source> to <destination> 
**		CP_BSS:	  Clear <length> bytes at <destination>
**		
**		End of table is indicated by an <action> with no bits set. 
** 
** destination:	Receiving address
**
** source:	Sending address
**
** length:	Length of data
*/

#define	CP_COPY		1
#define	CP_BSS		2

#ifdef _C88

typedef struct cp_entry {
	const unsigned char		cp_actions;	/* 1 byte  */
	_huge unsigned char *		cp_destin;	/* 3 bytes */
	_huge const unsigned char *	cp_source;	/* 3 bytes */
	unsigned long			cp_length;	/* 4 bytes */
} cp_entry_t;

extern _far const cp_entry_t	_lc_cp[];	        /* Copy table */
#endif

#define	LOCATE_INC

#endif

